services:
  reverse-web:
    image: nginx:stable-alpine
    hostname: reverse-web
    restart: always
    extra_hosts:
      - "host.docker.internal=host-gateway"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./locations:/etc/nginx/locations:ro"
      - "./configuration:/etc/nginx/configuration:ro"
      - "./sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./ssl:/etc/nginx/ssl"
      - "./logs:/var/log/nginx/"
    networks:
      - services
    ports:
      - 80:80
      - 443:443

networks:
  services:
    external: true
    driver: bridge
    name: services
