services:
    redis-cache:
        hostname: redis-cache
        container_name: redis-cache
        image: redis:5.0
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - backend

    redis-insight:
        image: redis/redisinsight:latest
        restart: always
        ports:
            - '5540:5540'
        volumes:
            - redis-insight:/data
        networks:
            - backend

volumes:
    redis_data:
    redis-insight:

networks:
    backend:
        external: true
